import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, CheckCircle, LockKeyhole, Radio, RefreshCw, Wallet, XCircle } from 'lucide-react'
import { ceoApi } from '../../api/index.js'
import { Card, EmptyState, Skeleton, StatCard, StatusBadge } from '../../components/ui/index.jsx'
import { formatKobo } from '../../utils/tracking.js'
import toast from 'react-hot-toast'

export default function CEOBrassDashboard() {
  const qc = useQueryClient()
  const [windowType, setWindowType] = useState('DAILY')
  const [events, setEvents] = useState([])
  const metrics = useQuery({ queryKey: ['ceo-contract-metrics'], queryFn: () => ceoApi.metrics().then(r => r.data), refetchInterval: 60000 })
  const telemetry = useQuery({ queryKey: ['ceo-contract-telemetry'], queryFn: () => ceoApi.telemetry().then(r => r.data), refetchInterval: 60000 })
  const data = metrics.data || {}
  const ledger = data.escrowLedger || data.escrow || {}
  const kyc = Array.isArray(data.kycQueue) ? data.kycQueue : data.kycQueue?.items || []
  const payouts = Array.isArray(data.payoutQueue) ? data.payoutQueue : data.payoutQueue?.items || []
  const adjudicate = useMutation({ mutationFn: ({ id, action }) => ceoApi.adjudicate({ targetUserId: id, action }), onSuccess: () => { toast.success('KYC queue updated'); qc.invalidateQueries({ queryKey: ['ceo-contract-metrics'] }) }, onError: e => toast.error(e.response?.data?.message || 'Adjudication failed') })
  const revoke = useMutation({ mutationFn: id => ceoApi.revokeAccess({ targetUserId: id }), onSuccess: () => { toast.success('Access revoked'); qc.invalidateQueries({ queryKey: ['ceo-contract-metrics'] }) }, onError: e => toast.error(e.response?.data?.message || 'Revoke failed') })
  const escrow = useMutation({ mutationFn: type => ceoApi.escrow({ settlementWindow: type }), onSuccess: () => toast.success('Settlement window saved'), onError: e => toast.error(e.response?.data?.message || 'Could not save settlement window') })

  useEffect(() => { const incoming = telemetry.data?.events || telemetry.data?.stream || []; if (Array.isArray(incoming)) setEvents(incoming.slice(-8).reverse()) }, [telemetry.data])
  const liveGmv = telemetry.data?.gmvKobo ?? telemetry.data?.liveGmvKobo ?? data.gmvKobo ?? 0

  return <div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-label mb-1">GIMBIYA COS / Brass</p><h1 className="font-display text-3xl font-bold text-text-p">Executive Command</h1><p className="text-text-m mt-1">Platform-wide treasury, KYC, and live operations.</p></div><button onClick={() => { qc.invalidateQueries({ queryKey: ['ceo-contract-metrics'] }); qc.invalidateQueries({ queryKey: ['ceo-contract-telemetry'] }) }} className="btn-icon" title="Refresh metrics"><RefreshCw className="w-4 h-4" /></button></header>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard label="Live GMV" value={formatKobo(liveGmv)} icon={Activity} /><StatCard label="Escrow locked" value={formatKobo(ledger.lockedKobo ?? ledger.locked ?? 0)} icon={LockKeyhole} color="text-warning" /><StatCard label="Escrow released" value={formatKobo(ledger.releasedKobo ?? ledger.released ?? 0)} icon={CheckCircle} color="text-success" /><StatCard label="Payout queue" value={payouts.length.toLocaleString()} icon={Wallet} color="text-role-affiliate" /></div>
    <div className="grid lg:grid-cols-3 gap-4"><Card className="lg:col-span-2"><div className="flex items-center justify-between mb-4"><p className="section-label">Live telemetry</p><span className="flex items-center gap-2 text-xs text-success"><Radio className="w-3 h-3" /> LIVE</span></div>{telemetry.isLoading ? <div className="space-y-2">{[1, 2, 3].map(i => <Skeleton key={i} className="h-12" />)}</div> : !events.length ? <EmptyState icon={Activity} title="No live events" description="Order and inventory stream events will appear here." /> : <div className="space-y-2">{events.map((event, index) => <div key={event.id || event._id || index} className="flex items-center justify-between gap-3 p-3 bg-midnight border border-border rounded-btn"><div><p className="text-sm text-text-p">{event.type || event.event || 'Platform event'}</p><p className="text-xs text-text-m">{event.orderId || event.productId || event.message || 'Telemetry received'}</p></div><span className="text-[10px] text-text-d">{event.createdAt ? new Date(event.createdAt).toLocaleTimeString('en-NG') : 'NOW'}</span></div>)}</div>}</Card><Card><p className="section-label">Settlement HUD</p><p className="text-xs text-text-m mt-1">Choose when released escrow settles.</p><div className="space-y-2 mt-4">{['DAILY', 'WEEKLY', 'MANUAL'].map(option => <label key={option} className="flex items-center gap-3 p-3 rounded-btn border border-border bg-midnight cursor-pointer"><input type="radio" name="settlement" checked={windowType === option} onChange={() => setWindowType(option)} /> <span className="text-sm text-text-p">{option === 'DAILY' ? 'Daily 6PM' : option[0] + option.slice(1).toLowerCase()}</span></label>)}</div><button className="btn btn-primary w-full mt-4" onClick={() => escrow.mutate(windowType)} disabled={escrow.isPending}>Save window</button></Card></div>
    <Card><div className="flex items-center justify-between mb-4"><div><p className="section-label">KYC adjudication queue</p><p className="text-xs text-warning mt-1">{kyc.length} awaiting decision</p></div></div>{!kyc.length ? <EmptyState icon={CheckCircle} title="Queue clear" description="No pending KYC adjudication." /> : <div className="space-y-2">{kyc.map((item, index) => <div key={item._id || item.id || index} className="flex flex-wrap items-center justify-between gap-3 p-3 bg-midnight border border-border rounded-btn"><div><p className="text-sm text-text-p">{item.name || item.email || 'Applicant'}</p><p className="text-xs text-text-m">{item.role || 'User'} · {item.assignedState || 'Platform'}</p></div><div className="flex items-center gap-2"><StatusBadge status={item.status || item.kycStatus || 'PENDING'} /><button className="btn-icon !text-success" title="Approve KYC" onClick={() => adjudicate.mutate({ id: item._id || item.id, action: 'APPROVE' })}><CheckCircle className="w-4 h-4" /></button><button className="btn-icon !text-danger" title="Revoke access" onClick={() => revoke.mutate(item._id || item.id)}><XCircle className="w-4 h-4" /></button></div></div>)}</div>}</Card>
  </div>
}
