import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BarChart3, CheckCircle, Store, TrendingUp, XCircle } from 'lucide-react'
import { Bar, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { storeApi, trackingApi } from '../../api/index.js'
import { Card, EmptyState, Skeleton, StatCard, StatusBadge } from '../../components/ui/index.jsx'
import { formatKobo, listFrom, percent } from '../../utils/tracking.js'
import toast from 'react-hot-toast'

export default function CoordinatorTrackingDashboard() {
  const qc = useQueryClient()
  const [status, setStatus] = useState('ALL')
  const region = useQuery({ queryKey: ['tracking-coordinator'], queryFn: () => trackingApi.coordinator().then(r => r.data), refetchInterval: 60000 })
  const data = region.data || {}
  const merchants = listFrom(data, ['merchants', 'shops', 'storeRequests']).filter(item => status === 'ALL' || item.status === status)
  const approve = useMutation({ mutationFn: id => storeApi.approveRequest(id, {}), onSuccess: () => { toast.success('Merchant approved'); qc.invalidateQueries({ queryKey: ['tracking-coordinator'] }) }, onError: e => toast.error(e.response?.data?.message || 'Approval failed') })
  const reject = useMutation({ mutationFn: id => storeApi.rejectRequest(id, { reason: 'Rejected by regional coordinator' }), onSuccess: () => { toast.success('Merchant rejected'); qc.invalidateQueries({ queryKey: ['tracking-coordinator'] }) }, onError: e => toast.error(e.response?.data?.message || 'Rejection failed') })
  const weekly = listFrom(data, ['weeklyGmv', 'weeklyGMV', 'weekly']).map((item, index) => ({ name: item.day || item.label || `W${index + 1}`, gmv: Number(item.gmvKobo ?? item.grossMerchandiseValueKobo ?? item.value ?? 0) / 100 }))
  const activeShops = data.activeShops ?? data.activeShopsCount ?? 0
  const fulfillment = data.fulfillmentPercent ?? data.fulfillmentRate ?? 0
  const kycQueue = data.kycQueuePending ?? data.kycQueue?.length ?? 0

  return <div className="space-y-6"><header><p className="section-label mb-1">Regional Operations</p><h1 className="font-display text-3xl font-bold text-text-p">Coordinator Control Room</h1><p className="text-text-m mt-1">State-scoped GMV, merchant approvals, and fulfillment health.</p></header>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><StatCard label="Regional GMV" value={formatKobo(data.gmvKobo ?? data.regionalGmvKobo)} icon={TrendingUp} /><StatCard label="Active shops" value={activeShops.toLocaleString()} icon={Store} color="text-success" /><StatCard label="Fulfillment" value={percent(fulfillment)} icon={CheckCircle} color="text-brass" /><StatCard label="KYC queue" value={kycQueue.toLocaleString()} icon={BarChart3} color="text-warning" /></div>
    <div className="grid lg:grid-cols-5 gap-4"><Card className="lg:col-span-2"><p className="section-label">Regional targets</p><div className="space-y-5 mt-5"><div><div className="flex justify-between text-sm mb-2"><span className="text-text-m">GMV target</span><span className="font-mono text-brass">{formatKobo(500000000)}</span></div><div className="h-2 bg-surface-h rounded-full"><div className="h-full bg-brass rounded-full" style={{ width: `${Math.min(100, (data.gmvKobo || 0) / 500000000 * 100)}%` }} /></div></div><div><div className="flex justify-between text-sm mb-2"><span className="text-text-m">Active shop target</span><span className="font-mono text-success">{activeShops} / 50+</span></div><div className="h-2 bg-surface-h rounded-full"><div className="h-full bg-success rounded-full" style={{ width: `${Math.min(100, activeShops / 50 * 100)}%` }} /></div></div></div></Card><Card className="lg:col-span-3"><p className="section-label mb-4">Weekly GMV</p>{region.isLoading ? <Skeleton className="h-56" /> : !weekly.length ? <EmptyState icon={TrendingUp} title="No GMV data" description="Weekly regional activity will appear here." /> : <ResponsiveContainer width="100%" height={220}><BarChart data={weekly}><CartesianGrid stroke="#292941" vertical={false} /><XAxis dataKey="name" stroke="#777791" fontSize={11} /><YAxis stroke="#777791" fontSize={11} tickFormatter={value => `₦${value.toLocaleString('en-NG')}`} /><Tooltip formatter={value => formatKobo(value * 100)} contentStyle={{ background: '#121226', border: '1px solid #353552' }} /><Bar dataKey="gmv" fill="#C8A84B" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer>}</Card></div>
    <Card><div className="flex flex-wrap items-center justify-between gap-3 mb-4"><div><p className="section-label">Merchants in my state</p><p className="text-xs text-text-m mt-1">Approve or reject pending store requests.</p></div><select className="input !w-auto !py-2" value={status} onChange={e => setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="PENDING">Pending</option><option value="APPROVED">Approved</option></select></div>{region.isLoading ? <div className="space-y-2">{[1, 2, 3].map(i => <Skeleton key={i} className="h-14" />)}</div> : !merchants.length ? <EmptyState icon={Store} title="No merchants found" description="There are no merchants matching this state and status." /> : <div className="space-y-2">{merchants.map((merchant, index) => <div key={merchant._id || merchant.id || index} className="flex flex-wrap items-center justify-between gap-3 p-3 bg-midnight border border-border rounded-btn"><div><p className="text-sm font-semibold text-text-p">{merchant.businessName || merchant.merchantName || merchant.name}</p><p className="text-xs text-text-m">{merchant.state || merchant.assignedState || 'Assigned state'} · {merchant.email || merchant.businessEmail || 'No email'}</p></div><div className="flex items-center gap-2"><StatusBadge status={merchant.status || 'PENDING'} />{(merchant.status || 'PENDING') === 'PENDING' && <><button className="btn-icon !text-success" title="Approve merchant" onClick={() => approve.mutate(merchant._id || merchant.id)}><CheckCircle className="w-4 h-4" /></button><button className="btn-icon !text-danger" title="Reject merchant" onClick={() => reject.mutate(merchant._id || merchant.id)}><XCircle className="w-4 h-4" /></button></>}</div></div>)}</div>}</Card>
  </div>
}
